# Generated by Django 4.1.5 on 2023-01-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=256)),
                ('datos_curiosos', models.CharField(max_length=256)),
                ('esta_buena_la_informacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tiempo_de_preparacion', models.IntegerField()),
                ('equipos_para_la_preparacion', models.CharField(max_length=256)),
                ('ingredientes', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('profesion', models.CharField(max_length=64)),
                ('bio', models.TextField()),
            ],
        ),
    ]
