# Generated by Django 4.1.5 on 2023-01-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_curiosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_curiosos', models.CharField(max_length=256)),
                ('esta_buena_la_informacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Consejos',
        ),
        migrations.AddField(
            model_name='receta',
            name='consejos',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
