# Generated by Django 4.0.4 on 2023-01-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_datos_curiosos_delete_consejos_receta_consejos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='tiempo_de_preparacion',
            field=models.CharField(max_length=24),
        ),
    ]
